Add an example of how to use kind
rabbitmq/rabbitmq-peer-discovery-k8s pull request #62
Opened 2019-12-17 20:30 UTC by Gsantomaggio

## Proposed Changes
Add an example of how to use [`kind`](https://github.com/kubernetes-sigs/kind)
Kind is K8s tools  for local tests and CI integrations

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes issue #NNNN)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause an observable behavior change in existing systems)
- [x] Documentation improvements (corrections, new content, etc)
- [ ] Cosmetic change (whitespace, formatting, etc)

## Checklist

- [x] I have read the `CONTRIBUTING.md` document
- [x] I have signed the CA (see https://cla.pivotal.io/sign/rabbitmq)
- [ ] All tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in related repositories

## Further Comments

I wanted to push this example on my personal repository, but I thought that can be useful for the community. As always, feel free to close/ignore it :) 
Thank you

2019-12-17 21:11 UTC, yashbhutwala approved these changes
Nice change, especially like the persistence addition 😃

2019-12-18 04:37 UTC, michaelklishin requested changes
Thank you. This could use a bit of editing. I'm happy to do some rewording after merging but let's address some things that immediately stand out first.

2019-12-18 04:37 UTC, michaelklishin commented on examples/kind/README.md
> +  $ kind create cluster --config kind/kind-cluster/kind-cluster.yaml
We don't use `$` to indicate a shell input in our examples. Please drop it.

2019-12-18 04:37 UTC, michaelklishin commented on examples/kind/README.md
> +Deploy RabbitMQ with or without [persistent-volumes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/).
The hyphen in `persistent-volumes` seems unnecessary?

2019-12-18 04:37 UTC, michaelklishin commented on examples/kind/README.md
> +     nodePort: 31672 <---- binds the extraPortMappings.containerPort 31672
Can this be a regular YAML comment?

2019-12-18 04:37 UTC, michaelklishin commented on examples/kind/README.md
> +CleanUP RabbitMQ without PV:
It should either be "clean-up" (a noun) or "clean up" (a verb). The title is probably meant to be a noun. CleanUP sounds like an unfortunate product name 🤣

2019-12-18 08:07 UTC, Gsantomaggio commented
ok done!

2019-12-19 22:11 UTC, michaelklishin approved these changes

2019-12-19 22:11 UTC, merged

2019-12-19 22:11 UTC, michaelklishin commented
Thank you!